print ("Welcome to the tip calculator.")
print ("What was the total bill? $")
bill = input()
bill = float(bill)
print ("How many people are going to split the bill?")
splitnumber = input()
splitnumber = int(splitnumber)
print ("What's the tip percentage you'd like to give - 10, 12 or 15%?")
tip = input()
tip = float(tip)
tip = tip/100
total = float(bill+(tip*bill))
eachPersonPays = (total/splitnumber)
eachPersonPays = round(eachPersonPays, 2)
print ("Each person has to pay "+str(eachPersonPays))
