from turtle import Turtle
import turtle
# NSFW

voldetort = Turtle()
voldetort.shape("circle")
voldetort.color("wheat2")
voldetort.pensize(15)

voldetort.forward(400)
voldetort.right(20)
voldetort.forward(18)
voldetort.right(20)
voldetort.forward(18)
voldetort.right(20)
voldetort.forward(18)
voldetort.right(20)
voldetort.forward(18)
voldetort.right(20)
voldetort.forward(18)
voldetort.right(20)
voldetort.forward(18)
voldetort.right(20)
voldetort.forward(18)
voldetort.right(20)
voldetort.forward(18)
voldetort.right(20)
voldetort.forward(18)
voldetort.forward(400)
voldetort.left(75)
voldetort.forward(20)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(10)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.left(100)
voldetort.forward(15)
voldetort.left(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(15)
voldetort.right(20)
voldetort.forward(20)
voldetort.left(50)
voldetort.forward(40)




screen = turtle.Screen()
screen.exitonclick()
